# Generated by Django 5.1.1 on 2025-02-18 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('booking', '0001_initial'),
        ('footboll_stadium', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='footboll_stadium.footballstadium'),
        ),
    ]
