# Generated by Django 5.1.1 on 2025-02-24 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='Pending', max_length=20),
        ),
    ]
