# Generated by Django 5.1.1 on 2025-02-18 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('footboll_stadium', '0003_alter_footballstadium_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='footballstadium',
            options={'ordering': ['name'], 'verbose_name': 'Stadium', 'verbose_name_plural': 'Stadiums'},
        ),
    ]
