# Generated by Django 5.1.1 on 2025-02-19 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('footboll_stadium', '0004_alter_footballstadium_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footballstadium',
            name='price_per_hour',
        ),
    ]
