# Generated by Django 5.1.1 on 2025-02-11 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FootballField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('contact', models.TextField(blank=True, max_length=250)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='stadium/')),
                ('price_per_hour', models.DecimalField(decimal_places=2, max_digits=10)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Football Field',
                'verbose_name_plural': 'Football Fields',
                'ordering': ['name'],
            },
        ),
    ]
