# Generated by Django 5.1.1 on 2025-02-19 04:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footboll_field', '0001_initial'),
        ('footboll_stadium', '0005_remove_footballstadium_price_per_hour'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footballfield',
            name='address',
        ),
        migrations.RemoveField(
            model_name='footballfield',
            name='bookings',
        ),
        migrations.RemoveField(
            model_name='footballfield',
            name='bookings_total_price',
        ),
        migrations.RemoveField(
            model_name='footballfield',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='footballfield',
            name='description',
        ),
        migrations.RemoveField(
            model_name='footballfield',
            name='owner',
        ),
        migrations.AddField(
            model_name='footballfield',
            name='stadium',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='football_fields', to='footboll_stadium.footballstadium'),
            preserve_default=False,
        ),
    ]
