# Generated by Django 5.1.1 on 2025-02-20 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('footboll_field', '0001_initial'),
        ('footboll_stadium', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='footballfield',
            name='stadium',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='football_fields', to='footboll_stadium.footballstadium'),
        ),
    ]
