# Generated by Django 5.1.1 on 2025-02-19 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footboll_field', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='footballfield',
            name='address',
            field=models.TextField(blank=True),
        ),
    ]
