# Generated by Django 5.1.1 on 2025-02-20 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('footboll_field', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footballfield',
            name='address',
        ),
    ]
