# Generated by Django 5.1.1 on 2025-02-19 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('footboll_field', '0003_footballfield_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footballfield',
            name='address',
        ),
    ]
