# Generated by Django 5.1.1 on 2025-02-19 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footboll_field', '0004_remove_footballfield_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='footballfield',
            name='address',
            field=models.TextField(blank=True),
        ),
    ]
